ecopret/src/Entity/Transaction.php
<?php

namespace App\Entity;

use App\Repository\TransactionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Monolog\Handler\Curl\Util;

#[ORM\Entity(repositoryClass: TransactionRepository::class)]
class Transaction
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToMany(targetEntity: Compte::class, mappedBy: 'transactions')]
    private Collection $comptes;

    #[ORM\ManyToOne(inversedBy: 'transaction')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Annonce $annonce = null;

    #[ORM\OneToMany(mappedBy: 'transaction', targetEntity: Litige::class, orphanRemoval: true)]
    private Collection $litiges;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Prestataire $Prestataire = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $Client = null;

    #[ORM\Column]
    private ?bool $est_cloture = null;

    #[ORM\Column]
    private ?bool $est_note = false;

    public function __construct()
    {
        $this->comptes = new ArrayCollection();
        $this->litiges = new ArrayCollection();
        $this->est_cloture = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Compte>
     */
    public function getComptes(): Collection
    {
        return $this->comptes;
    }

    public function addCompte(Compte $compte): static
    {
        if (!$this->comptes->contains($compte)) {
            $this->comptes->add($compte);
            $compte->addTransaction($this);
        }

        return $this;
    }

    public function removeCompte(Compte $compte): static
    {
        if ($this->comptes->removeElement($compte)) {
            $compte->removeTransaction($this);
        }

        return $this;
    }

    public function getAnnonce(): ?Annonce
    {
        return $this->annonce;
    }

    public function setAnnonce(?Annonce $annonce): static
    {
        $this->annonce = $annonce;

        return $this;
    }

    /**
     * @return Collection<int, Litige>
     */
    public function getLitiges(): Collection
    {
        return $this->litiges;
    }

    public function addLitige(Litige $litige): static
    {
        if (!$this->litiges->contains($litige)) {
            $this->litiges->add($litige);
            $litige->setTransaction($this);
        }

        return $this;
    }

    public function removeLitige(Litige $litige): static
    {
        if ($this->litiges->removeElement($litige)) {
            // set the owning side to null (unless already changed)
            if ($litige->getTransaction() === $this) {
                $litige->setTransaction(null);
            }
        }

        return $this;
    }

    public function getPrestataire(): ?Prestataire
    {
        return $this->Prestataire;
    }

    public function setPrestataire(?Prestataire $Prestataire): static
    {
        $this->Prestataire = $Prestataire;

        return $this;
    }

    public function getClient(): ?Utilisateur
    {
        return $this->Client;
    }

    public function setClient(?Utilisateur $Client): static
    {
        $this->Client = $Client;

        return $this;
    }

    public function isEstCloture(): ?bool
    {
        return $this->est_cloture;
    }

    public function setEstCloture(bool $est_cloture): static
    {
        $this->est_cloture = $est_cloture;

        return $this;
    }

    public function isEstNote(): ?bool
    {
        return $this->est_note;
    }

    public function setEstNote(bool $est_note): static
    {
        $this->est_note = $est_note;

        return $this;
    }
}

ecopret/templates/choisir/choisir.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	{{ parent() }}

	{% if bool_prix %}
		<link rel="stylesheet" href="{{ asset('css/choisir.css') }}">
	{% endif %}

	{% if not bool_prix or no_dispo %}
		<link rel="stylesheet" href="{{ asset('css/choisir2.css') }}">
	{% endif %}
{% endblock %}

{% block title %}Confirmation
{% endblock %}

{% block body %}
<div class="arh">
	<h3>Voici le récapitulatif de l'annonce</h3>
	<div class="card" id="card">
		<div class="card__title">
			<h4 class="center">{{ annonceCliquee.getNomAnnonce()|replace({"&amp;#039;": "'", "&quot;":"\""}) }} 
			{% if note >= 0 %}
			{{note}}&#9733; /5
			{% endif %}
			</h4>
				</div>
				<div class="card__content_img">
					{% if annonceCliquee.getImageAnnonce is defined and annonceCliquee.getImageAnnonce|split('|') is iterable %}
						{% set images = annonceCliquee.getImageAnnonce|split('|') %}
						{% if images|length > 0 %}
							<img src="{{ '/picturesAnnouncement/' ~ images[0] }}" width="150" height="150" id="imge1">
			{% else %}
				<img src="/picturesAnnouncement/" width="150" height="150" id="imge1" alt="">
			{% endif %}
			{% if images|length > 1 %}
				<img src="{{ '/picturesAnnouncement/' ~ images[1] }}" width="150" height="150" id="imge2" alt="">
			{% else %}
				<img src="/picturesAnnouncement/" width="150" height="150" id="imge2" alt="">
			{% endif %}
			{% if images|length > 2 %}
				<img src="{{ '/picturesAnnouncement/' ~ images[2] }}" width="150" height="150" id="imge3" alt="">
			{% else %}
				<img src="/picturesAnnouncement/" width="150" height="150" id="imge3" alt="">
			{% endif %}
		{% endif %}
	</div>
	<div class="card__content">
		<p class="center">{{ annonceCliquee.description|replace({"&amp;#039;": "'"})|replace({"&amp;#039;": "'", "&quot;":"\""}) }}</p>
				</div>
				<div class="card__content">
					<p class="center">{{annonceCliquee.prix}}</p>
					<img src="/img/florain.png" width="48" height="48" id="florain">
				</div>
                <div class="card__content">
                    <p class="center">Catégorie : {{annonceCliquee.getCategorie}}</p>
                </div>
			</div>
{% if bool_prix and not no_dispo %}
<h3>Etes vous certain de confirmer le choix de '{{ annonceCliquee.getNomAnnonce }}' ?</h3>

<h3 class="choisir_disponibites">Voici les disponibilités : </h3>
<div class="liste_dispo">
    <ol>
    {% for dispo in listeDisponibilite %}
        <li class="choisir_disponibites">{{ dispo }}</li>
    {% endfor %}
    </ol>
</div>

{{ form_start(choisirAnnonce) }}
<div class="button_cancel">
    {{ form_row(choisirAnnonce.numero_choix )}}
    {{ form_row(choisirAnnonce.oui) }}
    {{ form_row(choisirAnnonce.non) }}
		<button><a href="/echange/{{annonceCliquee.getId}}" style="text-decoration: none; color : white;">Demande d'échange</a></button>
	<button><a href="/conversation/creer/{{annonceCliquee.prestataire.id}}" style="text-decoration: none; color : white;">Contacter</a></button>
</div>
{{ form_end(choisirAnnonce) }}

{% endif %}


{% if not bool_prix %}
<h3>Etes vous certain de confirmer le choix de '{{ annonceCliquee.getNomAnnonce }}' ?</h3>

<h3 class="choisir_disponibites">Voici les disponibilités :</h3>
<ol>
    {% for dispo in listeDisponibilite %}
        <li class="choisir_disponibites">{{ dispo }}</li>
    {% endfor %}
</ol>
<h3>Vous n'avez pas assez de florains !</h3>

{{ form_start(choisirAnnonce) }}
<div class="button_cancel">
    {{ form_row(choisirAnnonce.numero_choix )}}
    {{ form_row(choisirAnnonce.oui) }}
    {{ form_row(choisirAnnonce.non) }}
</div>
{{ form_end(choisirAnnonce) }}

{% endif %}


{% if bool_prix and no_dispo %}
<h3>Etes vous certain de confirmer le choix de '{{ annonceCliquee.getNomAnnonce }}' ?</h3>

<h3 class="choisir_disponibites">Aucune disponibilité ! <br>Vous pouvez vous inscrire sur liste d'attente. <br> Vous recevrez un mail dès que le prestataire aura rajouté des disponibilités</h3>
<div class="btn">
    {% if DejaAjouter is same as(null) %}
    <div class="">
        {{form_start(listeAttente)}}
            {{form_row(listeAttente.Ajouter)}}
        {{form_end(listeAttente)}}
		<button><a href="/conversation/creer/{{annonceCliquee.prestataire.id}}" style="text-decoration: none; color : white;">Contacter</a></button>
    </div>
    {% else %}
        <h3>Cette annonce est déjà dans votre file d'attente</h3>
    {% endif %}

    {{ form_start(choisirAnnonce) }}
    <div class="button_cancel">
        {{ form_row(choisirAnnonce.numero_choix )}}
        {{ form_row(choisirAnnonce.oui) }}
        {{ form_row(choisirAnnonce.non) }}
    </div>

{{ form_end(choisirAnnonce) }}
</div>
</div>
{% endif %}
{% endblock %} 